services:
    phlexible_indexer_storage_elastica.query_mapper:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\Storage\QueryMapper

    phlexible_indexer_storage_elastica.adapter:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\Storage\ElasticsearchStorageAdapter
        arguments:
            - @phlexible_elastica.default_client
            - @phlexible_indexer_storage_elastica.query_mapper

    phlexible_indexer_storage_elastica.storage:
        class: Phlexible\Bundle\IndexerBundle\Storage\Storage
        arguments: [@event_dispatcher, @phlexible_indexer_storage_elastica.adapter]
        tags:
            - {name: phlexible_indexer.storage}

    # problem checks
    phlexible_indexer_storage_elastica.service_check:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\ProblemChecker\ServiceChecker
        arguments: [@phlexible_elastica.default_client]
        tags:
            - {name: phlexible_problem.checker}
