services:
    phlexible_indexer_storage_elastica.elastica_storage:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\Storage\ElasticaStorage
        arguments:
            - @phlexible_elastica.default_client
            - @phlexible_indexer_storage_elastica.elastica_mapper
            - @phlexible_indexer.update_query
            - @event_dispatcher
            - test2

    phlexible_indexer_storage_elastica.elastica_mapper:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\Storage\ElasticaMapper
        arguments:
            - @phlexible_indexer.document_factory

    # problem checks
    phlexible_indexer_storage_elastica.service_check:
        class: Phlexible\Bundle\IndexerStorageElasticaBundle\ProblemChecker\ServiceChecker
        arguments: [@phlexible_elastica.default_client]
        tags:
            - {name: phlexible_problem.checker}
